---
name: Test

on: pull_request  # yamllint disable-line rule:truthy

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.10'
          - '3.11'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - name: Build the wheel
        run: poetry build -f wheel
      - name: Typecheck with pyright
        uses: jakebailey/pyright-action@v1
      - name: Check type completeness with pyright
        uses: jakebailey/pyright-action@v1
        with:
          ignore-external: true
          verify-types: greeneye
      - name: Run tests
        run: poetry run pytest
